#!/usr/bin/env python3
"""Render skills/trustgrowth/references/contract.md from the TrustGrowth capability manifest.

The manifest (GET /api/v1/capabilities/v1) is the source of truth for what
Groundcrew may call. This file is never hand-edited: regenerate it from the
vendored manifest, or from the live server with --from-live, and commit both.
"""
import argparse, json, os, pathlib, sys, urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "shared" / "contract" / "capabilities.json"
PIN = ROOT / "shared" / "contract-pin.json"
OUTPUT = ROOT / "skills" / "trustgrowth" / "references" / "contract.md"

ERROR_MEANINGS = {
    "401": "Missing or invalid API key. Stop; ask the owner to set `TRUSTGROWTH_API_KEY`.",
    "402": "Credits required. Body carries the quote; never retry without owner approval.",
    "403": "Scope or plan gate. Body has `error.code` (`plan_limit` with `required_feature` / `upgrade_to`, or a scope error). Report it verbatim; do not guess.",
    "404": "Unknown slug or a site this key cannot see. Re-list `GET /api/v1/sites`.",
    "405": "Wrong HTTP method for this path.",
    "409": "State conflict (for example an agent already running, or a stale version). Read the body; do not retry blindly.",
    "422": "Invalid params. The message names the field; fix the call.",
    "429": "Rate limited. Honour `Retry-After` / `X-RateLimit-*` headers, then retry once.",
}

PATH_PARAMS = {"slug", "entry_uid", "campaign_uid", "review_uid", "job_id", "session_uid", "uid"}


def load_manifest(source):
    if source == "live":
        key = os.getenv("TRUSTGROWTH_API_KEY")
        if not key:
            sys.exit("--from-live needs TRUSTGROWTH_API_KEY")
        base = os.getenv("TRUSTGROWTH_API_BASE", "https://trustgrowth.ai").rstrip("/")
        req = urllib.request.Request(base + "/api/v1/capabilities/v1", headers={
            "Authorization": f"Bearer {key}", "Accept": "application/json",
            "User-Agent": "Groundcrew-Contract/0.4 (+https://github.com/techwright-lab/groundcrew)",
        })
        with urllib.request.urlopen(req, timeout=20) as response:
            return json.load(response)
    return json.loads(pathlib.Path(source).read_text())


def normalize(manifest):
    return {
        "version": manifest["version"],
        "contract_version": manifest.get("contract_version"),
        "generated_from": manifest.get("generated_from", []),
        "operations": sorted(manifest["operations"], key=lambda o: (o["endpoint"], o["method"])),
        "tools": sorted(manifest["tools"], key=lambda t: t["name"]),
        "dark_surfaces": sorted(manifest.get("dark_surfaces", []), key=lambda d: d["name"]),
    }


def params_cell(operation):
    query = [p for p in operation.get("parameters", []) if p["name"] not in PATH_PARAMS]
    if not query:
        return "—"
    return ", ".join(f"`{p['name']}`" + ("*" if p.get("required") else "") for p in query)


def render(manifest, pin):
    ops = manifest["operations"]
    reads = [o for o in ops if o["method"] == "GET"]
    writes = [o for o in ops if o["method"] != "GET"]
    tools_by_endpoint = {}
    for tool in manifest["tools"]:
        tools_by_endpoint.setdefault(tool["endpoint"], []).append(tool["name"])
    contract_version = manifest["contract_version"] or pin["contract_version"]
    lines = [
        "# TrustGrowth contract",
        "",
        "Generated by `scripts/gen-contract.py` from `GET /api/v1/capabilities/v1`. Do not edit by hand.",
        "",
        f"- Contract version: `{contract_version}` (pinned minimum `{pin['contract_version']}`; manifest `{manifest['version']}`)",
        "- Source of truth: the live manifest. If a call is not listed here, it does not exist for Groundcrew.",
        "- REST and MCP share one implementation; a tool name maps to exactly one REST path.",
        "- Envelope: `{ data, meta }`. `meta.rate_limit` mirrors the authoritative `X-RateLimit-*` / `Retry-After` headers.",
        "- Not measured is `null`, never `0`.",
        "",
        "## Reads (`read` scope)",
        "",
        "| Method | Path | Query params (`*` required) | MCP tool | Errors |",
        "|---|---|---|---|---|",
    ]
    for o in reads:
        tools = ", ".join(f"`{t}`" for t in tools_by_endpoint.get(o["endpoint"], [])) or "—"
        lines.append(f"| {o['method']} | `{o['endpoint']}` | {params_cell(o)} | {tools} | {' '.join(o['error_codes'])} |")
    lines += ["", "## Writes (`write`, `distribute`, or `claim_review` scope; credit-quoted)", "",
              "| Method | Path | Params (`*` required) | MCP tool | Scopes | Errors |", "|---|---|---|---|---|---|"]
    scopes_by_tool = {t["name"]: t["scopes"] for t in manifest["tools"]}
    for o in writes:
        names = tools_by_endpoint.get(o["endpoint"], [])
        tools = ", ".join(f"`{t}`" for t in names) or "—"
        scopes = ", ".join(sorted({s for n in names for s in scopes_by_tool.get(n, [])})) or "—"
        lines.append(f"| {o['method']} | `{o['endpoint']}` | {params_cell(o)} | {tools} | {scopes} | {' '.join(o['error_codes'])} |")
    lines += ["", "## MCP tools", "", "Streamable HTTP at `POST $TRUSTGROWTH_API_BASE/mcp`. Name the tool, not the URL; fall back to the REST path in the same row.", "",
              "| Tool | REST path | Scopes |", "|---|---|---|"]
    for t in manifest["tools"]:
        lines.append(f"| `{t['name']}` | `{t['endpoint']}` | {', '.join(t['scopes']) or '—'} |")
    lines += ["", "## Error codes", ""]
    for code in sorted({e for o in ops for e in o["error_codes"]}):
        lines.append(f"- `{code}` — {ERROR_MEANINGS.get(code, 'See the response body.')}")
    lines += ["", "## Dark surfaces", "",
              "Present on the server, withheld from Groundcrew. Never call, document, or imply them.", ""]
    lines += [f"- `{d['name']}`" for d in manifest["dark_surfaces"]]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--from", dest="source", default=str(MANIFEST), help="manifest JSON path (default: vendored)")
    parser.add_argument("--from-live", action="store_true", help="fetch the live manifest and refresh the vendored copy")
    parser.add_argument("--check", action="store_true", help="fail if the committed contract.md is stale")
    args = parser.parse_args()
    manifest = normalize(load_manifest("live" if args.from_live else args.source))
    pin = json.loads(PIN.read_text())
    if args.from_live:
        MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    rendered = render(manifest, pin)
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != rendered:
            print(f"stale: {OUTPUT.relative_to(ROOT)} — run scripts/gen-contract.py", file=sys.stderr)
            return 1
        print("contract.md is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(manifest['operations'])} operations, {len(manifest['tools'])} tools)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
